server:
  port: 7878

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password: cvenky
    driver-class-name: com.mysql.cj.jdbc.Driver
